const UserActionsType = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  SIGNIN_SUCCESS: "GOOGLE_SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGNOUT_START: "SIGNOUT_START",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILURE: "SIGNOUT_FAILURE",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE"
};

export default UserActionsType;